# 当前系统配置
server:
  name: quan-admin
  port: 9001
  env: localhost
  prefix: user

# nacos访问配置
nacos:
  address: localhost:8848
  path: /nacos
  username: nacos
  password: nacos
  mode: 0
  nameSpace: localhost
  logDir: .nacos/log
  cacheDir: .nacos/cache

# nacos配置清单
configs:
  - name: quan-admin
    group: service
    dataId: quan.admin.service.yaml
  - name: database
    group: common
    dataId: mysql.database.common.yaml
  - name: redis
    group: common
    dataId: redis.common.yaml