#source: default
#enable: true
#type: postgres
#host: localhost
#port: 5432
#username: postgres
#password: postgres
#database: quan_tools
#debug: true
#init: true

source: default
enable: true
type: mysql
host: localhost
port: 3306
username: root
password: mysql123qc
database: quan_user
debug: true
init: true