# 当前应用配置
server:
  name: quan-user
  port: 9001
  env: localhost
  prefix: user

# 数据库配置
database:
  - source: default
    enable: true
    type: postgres
    host: localhost
    port: 5432
    username: postgres
    password: postgres
    database: quan_user
    debug: true
    init: true

# redis配置
redis:
  - source: default
    mode: 0
    host: localhost
    port: 6379
    password: Init@123
    database: 1
  - source: user
    mode: 0
    host: localhost
    port: 6379
    password: Init@123
    database: 2