# 当前应用配置
server:
  name: quan-user
  port: 9001
  env: localhost
  prefix: user

# nacos访问配置
nacos:
  address: localhost:8848
  path: /nacos
  username: nacos
  password: nacos
  mode: 0
  nameSpace: localhost
  logDir: resource/.nacos/log
  cacheDir: resource/.nacos/cache
  options:
    - group: user
      dataId: server.yaml
    - group: user
      dataId: database.yaml
    - group: user
      dataId: redis.yaml
